# Generated by Django 4.2.5 on 2023-10-25 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_brand_bus_brand_rename_model_bus_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='amount',
            field=models.DecimalField(max_digits=10, decimal_places=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.CharField(max_length=20),
        ),
    ]
