# Generated by Django 4.2.5 on 2023-11-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_trip_amount_alter_trip_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='amount',
        ),
    ]
