# Generated by Django 4.2.5 on 2023-11-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_trip_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(default=50000, upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
