# Generated by Django 4.2.5 on 2023-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_trip_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='amount',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
