# Generated by Django 4.2.5 on 2023-11-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_trip_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='amount',
        ),
    ]
