# Generated by Django 4.2.5 on 2023-11-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_remove_trip_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
