# Generated by Django 4.2.5 on 2023-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_trip_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='amount',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
