# Generated by Django 4.2.5 on 2023-11-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_trip_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='photo',
        ),
    ]
