# Generated by Django 4.2.5 on 2023-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_remove_driver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
