# Generated by Django 4.2.5 on 2023-11-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_driver_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='amount',
        ),
    ]
