# Generated by Django 4.2.5 on 2023-11-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_remove_trip_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
