# Generated by Django 4.2.5 on 2023-11-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_trip_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
    ]
