# Generated by Django 4.2.5 on 2023-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_trip_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
