# Generated by Django 4.2.5 on 2023-11-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_bus_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='photo',
        ),
    ]
